### ISSUE TITLE
Cache and Nan

### ISSUE THREAD

**Issue by bakasaru** [bdm1981/finesseGadgets#18]
10.6 SU2 with IE11 we're seeing that the Time column always shows NaN, the seconds portion of the Duration also shows NaN, and the stats are not resetting/clearing each day.

**Comment by bdm1981** [comment]
This happens when IE is in compatibility mode. I am looking to update this. I will post my progress early next week.

**Comment by bakasaru** [comment]
We're not running Compatibility Mode as according to the docwiki Finesse only supports Native Mode with 10.6(1) and IE11.

**Comment by bdm1981** [comment]
What you are describing is exactly what happens in compatibility mode. Older versions of IE are unable to parse the date properly. This causes the NaN output and prevents the gadget from determining what the current day is. Since the gadget doesn't know the current day, the history never clears.

 If the domain for Finesse isn't listed here: 
![image](https://cloud.githubusercontent.com/assets/10137511/19617108/ec165a40-97ec-11e6-8c42-1418f3dfdcaa.png)

Check to make sure the document mode wasn't manually changed via the developer tools: Press F12 and check here: 
![image](https://cloud.githubusercontent.com/assets/10137511/19617113/1b4d6434-97ed-11e6-8556-9f430a394b6f.png)

I also just uploaded a new version of the code that enables the gadget to work in compatibility mode. I had a handful of people asking for this. If everything checks out of the settings above, give the latest code a shot and let me know the results.

**Comment by bakasaru** [comment]
Definitely not in Compatibility View list, however we did find that local policy has been setting IE to Enterprise Mode and that was causing most of the issues to date. Setting to Desktop and Edge fixed the anomalies we were seeing in Call History.

**Comment by bdm1981** [comment]
Excellent. The latest version of the code I uploaded should work for you in Enterprise Mode if you need to operate in that mode for some reason. If you do get a chance to test it, let me know the outcome so I can update my docs.

**Comment by bakasaru** [comment]
Everything has tested fine with just the addition of moment.js functionality (we’re still using the built-in jquery instead of 1.9.1) both with and without Enterprise Mode.  Thanks!
